### PR TITLE
Fix: Add Shipyard Intro and Update 'Submit Your Project' Button

### LINKED ISSUE #381: Shipyard Page Incomplete
## Description

The Shipyard page is incomplete, and the "Submit your project" link is broken.

## Reproduction

1. Navigate to the Shipyard page.
2. Observe the missing content and broken "Submit your project" link.

## Expectation

The Shipyard page should include:
1. A description of the Shipyard initiative.
2. Steps to submit a project.
3. A working "Submit your project" link.

## Environment

- Device: Any (Laptop, Mobile, Tablet)
- OS: Any (Windows, macOS, Linux, iOS, Android)
- Browser: Any (Chrome, Firefox, Safari, Edge)
- Version: Latest

## Additional context

Completing the Shipyard page will enhance user engagement and make it functional.

## Resolution

- [ ] I would be interested in resolving this bug.

### LINKED ISSUE #385: Complete Shipyard Page
## Problem

The Shipyard page is incomplete and does not provide detailed information about submitting projects or the initiative's purpose.

## Description

Complete the Shipyard page by:
1. Adding a detailed description of the initiative.
2. Including a step-by-step guide for submitting projects.
3. Ensuring the "Submit your project" link is functional.

## Alternatives

- Include a video tutorial for project submission.
- Link to an external document or GitHub README for project submission details.

## Additional context

A complete Shipyard page will attract more contributors and make the initiative more effective.

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by RaghavRR**
## Fixes

Fixes #381  by @RaghavRR
Fixes #385 by @RaghavRR

## Description

This pull request completes the **Shipyard Page** by adding the introduction section and updating the **"Submit your project"** button link to make it functional.

The new Shipyard intro explains the initiative and its purpose, while the button directs users to the correct **Shipyard GitHub repository**, where they can submit their projects after fork.

## Note for Reviewer:
The README.md file for the Shipyard project currently does not exist in the repository at the specified location (src/app/shipyard/README.md).
Once this pull request is reviewed and merged, I will create the necessary README.md file to include detailed project submission instructions, guidelines, and additional information for users.

In the meantime, please note that this file will be created after the merge.

## Technical details

- Added a new component, `ShipyardIntro`, which includes the introductory section for Shipyard.
- Updated the "Submit your project" link to ensure it redirects to the correct repository.
- Modified the Shipyard page to be more visually appealing and informative.

## Tests

- Navigate to the **Shipyard GitHub repository**.
- Verify that the "Submit your project" button works and redirects to the correct destination.
- Ensure the introduction section is displayed correctly with the new content.

## Screenshots

**Before:**
- 
before
before1

**After:**
- 
After1
After2
After3

### CODE REVIEW

**Review by Mr-Sunglasses — COMMENTED** [review]
Hey @RaghavRR, There are some problem during the process deploy preview process, the logs are

```
12:48:46 AM: build-image version: ba55f85ffe1878034fe03904205af79aa234f545 (focal)
12:48:46 AM: buildbot version: 766d2c1ac7b7596f18b546cb6bf13962d157b033
12:48:46 AM: Fetching cached dependencies
12:48:46 AM: Failed to fetch cache, continuing with build
12:48:46 AM: Starting to prepare the repo for build
12:48:46 AM: No cached dependencies found. Cloning fresh repo
12:48:46 AM: git clone --filter=blob:none https://github.com/FOSS-Community/fosscu.org
12:48:47 AM: Preparing Git Reference pull/393/head
12:48:48 AM: Custom build path detected. Proceeding with the specified path: ''
12:48:48 AM: Starting to install dependencies
12:48:49 AM: mise python@3.13.3   install
12:48:49 AM: mise python@3.13.3   download cpython-3.13.3+20250409-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz
12:48:49 AM: mise python@3.13.3   extract cpython-3.13.3+20250409-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz
12:48:50 AM: mise python@3.13.3   python --version
12:48:50 AM: mise python@3.13.3   Python 3.13.3
12:48:50 AM: mise python@3.13.3 ✓ installed
12:48:50 AM: Python version set to 3.13
12:48:51 AM: Collecting pipenv
12:48:51 AM:   Downloading pipenv-2025.0.1-py3-none-any.whl.metadata (17 kB)
12:48:51 AM: Collecting certifi (from pipenv)
12:48:51 AM:   Downloading certifi-2025.4.26-py3-none-any.whl.metadata (2.5 kB)
12:48:51 AM: Collecting packaging>=22 (from pipenv)
12:48:51 AM:   Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
12:48:51 AM: Collecting setuptools>=67 (from pipenv)
12:48:51 AM:   Downloading setuptools-80.0.0-py3-none-any.whl.metadata (6.5 kB)
12:48:51 AM: Collecting virtualenv>=20.24.2 (from pipenv)
12:48:51 AM:   Downloading virtualenv-20.30.0-py3-none-any.whl.metadata (4.5 kB)
12:48:52 AM: Collecting distlib<1,>=0.3.7 (from virtualenv>=20.24.2->pipenv)
12:48:52 AM:   Downloading distlib-0.3.9-py2.py3-none-any.whl.metadata (5.2 kB)
12:48:52 AM: Collecting filelock<4,>=3.12.2 (from virtualenv>=20.24.2->pipenv)
12:48:52 AM:   Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
12:48:52 AM: Collecting platformdirs<5,>=3.9.1 (from virtualenv>=20.24.2->pipenv)
12:48:52 AM:   Downloading platformdirs-4.3.7-py3-none-any.whl.metadata (11 kB)
12:48:52 AM: Downloading pipenv-2025.0.1-py3-none-any.whl (3.0 MB)
12:48:52 AM:    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 48.3 MB/s eta 0:00:00
12:48:52 AM: Downloading packaging-25.0-py3-none-any.whl (66 kB)
12:48:52 AM: Downloading setuptools-80.0.0-py3-none-any.whl (1.2 MB)
12:48:52 AM:    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 105.7 MB/s eta 0:00:00
12:48:52 AM: Downloading virtualenv-20.30.0-py3-none-any.whl (4.3 MB)
12:48:52 AM:    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 177.4 MB/s eta 0:00:00
12:48:52 AM: Downloading certifi-2025.4.26-py3-none-any.whl (159 kB)
12:48:52 AM: Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
12:48:52 AM: Downloading filelock-3.18.0-py3-none-any.whl (16 kB)
12:48:52 AM: Downloading platformdirs-4.3.7-py3-none-any.whl (18 kB)
12:48:52 AM: Installing collected packages: distlib, setuptools, platformdirs, packaging, filelock, certifi, virtualenv, pipenv
12:48:54 AM: Successfully installed certifi-2025.4.26 distlib-0.3.9 filelock-3.18.0 packaging-25.0 pipenv-2025.0.1 platformdirs-4.3.7 setuptools-80.0.0 virtualenv-20.30.0
12:48:54 AM: [notice] A new release of pip is available: 24.3.1 -> 25.1
12:48:54 AM: [notice] To update, run: pip install --upgrade pip
12:48:54 AM: Attempting Ruby version 2.7.2, read from environment
12:48:55 AM: Using Ruby version 2.7.2
12:48:55 AM: Started restoring cached go cache
12:48:55 AM: Finished restoring cached go cache
12:48:57 AM: go version go1.19.13 linux/amd64
12:48:57 AM: Using PHP version 8.0
12:48:59 AM: v22.15.0 is already installed.
12:48:59 AM: Now using node v22.15.0 (npm v10.9.2)
12:48:59 AM: Enabling Node.js Corepack
12:48:59 AM: Started restoring cached build plugins
12:48:59 AM: Finished restoring cached build plugins
12:48:59 AM: Started restoring cached corepack dependencies
12:48:59 AM: Finished restoring cached corepack dependencies
12:48:59 AM: No npm workspaces detected
12:48:59 AM: Started restoring cached node modules
12:48:59 AM: Finished restoring cached node modules
12:48:59 AM: Installing npm packages using npm version 10.9.2
12:49:10 AM: added 386 packages, and audited 387 packages in 10s
12:49:10 AM: 147 packages are looking for funding
12:49:10 AM:   run `npm fund` for details
12:49:10 AM: 1 critical severity vulnerability
12:49:10 AM: To address all issues, run:
12:49:10 AM:   npm audit fix --force
12:49:10 AM: Run `npm audit` for details.
12:49:10 AM: npm packages installed
12:49:10 AM: Successfully installed dependencies
12:49:10 AM: Starting build script
12:49:11 AM: Detected 1 framework(s)
12:49:12 AM: "next" at version "15.1.0"
12:49:12 AM: Section completed: initializing
12:49:13 AM: ​
12:49:13 AM: Netlify Build                                                 
12:49:13 AM: ────────────────────────────────────────────────────────────────
12:49:13 AM: ​
12:49:13 AM: ❯ Version
12:49:13 AM:   @netlify/build 32.1.0
12:49:13 AM: ​
12:49:13 AM: ❯ Flags
12:49:13 AM:   accountId: 6136e173100202fab3bc120f
12:49:13 AM:   baseRelDir: true
12:49:13 AM:   buildId: 680f87cee4f6600008577175
12:49:13 AM:   deployId: 680f87cee4f6600008577177
12:49:13 AM: ​
12:49:13 AM: ❯ Current directory
12:49:13 AM:   /opt/build/repo
12:49:13 AM: ​
12:49:13 AM: ❯ Config file
12:49:13 AM:   No config file was defined: using default values.
12:49:13 AM: ​
12:49:13 AM: ❯ Context
12:49:13 AM:   deploy-preview
12:49:13 AM: ​
12:49:13 AM: ❯ Installing plugins
12:49:13 AM:    - @netlify/plugin-lighthouse@6.0.1
12:49:13 AM:    - @netlify/plugin-nextjs@5.10.7
12:49:22 AM: ​
12:49:22 AM: ❯ Using Next.js Runtime - v5.10.7
12:49:22 AM: ​
12:49:22 AM: ❯ Loading plugins
12:49:22 AM:    - @netlify/plugin-lighthouse@6.0.1 from Netlify app
12:49:24 AM: No Next.js cache to restore
12:49:24 AM: ​
12:49:24 AM: Build command from Netlify app                                
12:49:24 AM: ────────────────────────────────────────────────────────────────
12:49:24 AM: ​
12:49:24 AM: $ npm run build
12:49:24 AM: > fosscu.org@0.1.0 build
12:49:24 AM: > next build
12:49:24 AM: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
12:49:24 AM:    ▲ Next.js 15.1.0
12:49:24 AM:    Creating an optimized production build ...
12:49:33 AM:  ✓ Compiled successfully
12:49:33 AM:    Linting and checking validity of types ...
12:49:34 AM: 
12:49:34 AM: Failed to compile.
12:49:34 AM: ./src/components/ShipyardIntro.tsx
12:49:34 AM: 19:31  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
12:49:34 AM: 20:24  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
12:49:34 AM: 20:55  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
12:49:34 AM: 39:36  Error: `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.  react/no-unescaped-entities
12:49:34 AM: 39:56  Error: `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.  react/no-unescaped-entities
12:49:34 AM: 40:71  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
12:49:34 AM: ./src/components/ui/hover-border-gradient.tsx
12:49:34 AM: 29:9  Warning: The 'rotateDirection' function makes the dependencies of useEffect Hook (at line 57) change on every render. Move it inside the useEffect callback. Alternatively, wrap the definition of 'rotateDirection' in its own useCallback() Hook.  react-hooks/exhaustive-deps
12:49:34 AM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
12:49:36 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:49:36 AM: ​
12:49:36 AM: "build.command" failed                                        
12:49:36 AM: ────────────────────────────────────────────────────────────────
12:49:36 AM: ​
12:49:36 AM:   Error message
12:49:36 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
12:49:36 AM: ​
12:49:36 AM:   Error location
12:49:36 AM:   In Build command from Netlify app:
12:49:36 AM:   npm run build
12:49:36 AM: ​
12:49:36 AM:   Resolved config
12:49:36 AM:   build:
12:49:36 AM:     base: /opt/build/repo
12:49:36 AM:     command: npm run build
12:49:36 AM:     commandOrigin: ui
12:49:36 AM:     environment:
12:49:36 AM:       - REACT_APP_AIRTABLE_SECRET_API_TOKEN
12:49:36 AM:       - REACT_APP_BASE_ID
12:49:36 AM:       - REVIEW_ID
12:49:36 AM:     publish: /opt/build/repo/.next
12:49:36 AM:     publishOrigin: ui
12:49:36 AM:   plugins:
12:49:36 AM:     - inputs: {}
12:49:36 AM:       origin: ui
12:49:36 AM:       package: '@netlify/plugin-lighthouse'
12:49:36 AM:     - inputs: {}
12:49:36 AM:       origin: ui
12:49:36 AM:       package: '@netlify/plugin-nextjs'
12:49:36 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:49:36 AM: Failing build: Failed to build site
12:49:36 AM: Finished processing build request in 50.301s
```

Please take a look to these logs.

**Comment by RaghavRR** [comment]
@Mr-Sunglasses I have fix the logs.. Please review.😊

## npm-run-build in my local machine
npm run build

## npm-run-dev in my local machine
npm run dev

File: src/app/shipyard/page.tsx [hunk 1]
```diff
@@ -84,19 +87,21 @@ export default function Shipyard() {
...
             transition={{ duration: 0.5, delay: 0.3 }}
+            animate={{ opacity: 1, y: 0 }}
             className="text-center"
-          >
+          > 
             <PrimaryButton
               onClick={() => {
-                // window.open('', '_blank');
+                alert("Hang tight! Submission steps will appear here once the pull request is approved. You'll soon be able to fork the repo and add your project idea.");
+                // window.open('https://github.com/FOSS-Community/fosscu.org/blob/main/src/app/shipyard/README.md', '_blank');
```
Comment (Mr-Sunglasses) [inline src/app/shipyard/page.tsx:97]: I think we need to redirect the user to the repo ? So you should uncomment it ?

**Review by Mr-Sunglasses — CHANGES_REQUESTED** [review]

File: src/app/shipyard/page.tsx (hunk 1 above)
Comment (RaghavRR) [reply src/app/shipyard/page.tsx:97]: Thank you @Mr-Sunglasses for the suggestion!

Currently, the README.md file we are trying to link will only be available after the pull request is approved and merged.

If we uncomment the link right now, users might get a 404 error because the file does not exist yet.

As an alternative, I have added an alert message to inform users that submission steps will be available soon.

Once the pull request is merged and the README is live, we can update the button to redirect users either directly to the README or to the repository homepage as you suggested.

**Review by Mr-Sunglasses — APPROVED** [review]
Thanks @RaghavRR for your PR!
